### ISSUE TITLE
Static data replace to HTTP request

### ISSUE THREAD

**Issue by platstar** [shershen08/vue.js-v2-crud-application#1]
If the products data come from HTTP request, how could  I  do?

I'm a newbie of Vue.
here is my code , but it doesn't work.
`
var app = new Vue({
  el: '#app',
  router: router,
  template: '<router-view></router-view>',
  mounted: function() {
      this.getData();
  },
  methods: {     
      getData: function (event) {
         axios.get('http://localhost:5942/xxxx')
            .then(function (response) {
                products = response.data;
                console.log(products);
            })
            .catch(function (error) {
                console.log(error);
            });
    }
  }
});
`

**Comment by shershen08** [comment]
Hi @platstar 
What error do you get with this code ? Something in the browser console?
Does the [console.log(products);](url) work out well ?
Could you try to reproduce it in some online editor, like http://jsfiddle.net or http://plnkr.co/edit/ ?

**Comment by platstar** [comment]
I have put my code on here, but It is not a complete.
Could you just take a look, Is it necessary to run it twice for getData() ? ( line:49 , 219 )
https://jsfiddle.net/platstar/u3u3nzns/19/

**Comment by shershen08** [comment]
@platstar i've checked your code. I think I got what you asking.

1) If it's the same data request - then you should not have it twice. You can either have it in the app initialization section (line ~219) and then [pass to components via props](https://vuejs.org/v2/api/#data).  Smth like this should work.
```

new Vue({
  data: {
    products: []
  },
   created: function () {
        this.getData();
    },
    methods: {
        getData: function (event) {
            axios.get(url_get)
               .then((response) => {
                   this.products = response.data;
               })
               .catch((error) => {
                   console.log(error);
               });
        }
    }

```

2) It may be another use case when some data requests are related to once specific component only and should be handled within this component, not on the root app level. For example you have /menu api call for list in `Menu` component or /posts call list in `Posts` component and then can be loaded when only needed. 

But in the simple demo app like this one that's not the case.

Hope that helps. Closing for now.
