### ISSUE TITLE
Integration with Backend

### ISSUE THREAD

**Issue by bparanj** [shershen08/vue.js-v2-crud-application#2]
How do I save the changes to a database in the backend?

**Comment by shershen08** [comment]
This repo does not contain any api calls yet that could save/read data from DB. You can add such code yourself in places like 'updateProduct' and other which change the model state.

**Comment by yohoGDES** [comment]
I have been looking for a tutorial of how to do this for a while but it seems like there are so many outdated examples. +1 for adding this in a separate repo or if you have any resources that could help to inform this topic.
